const UNLIMITED_KSC = 200000000

const PackageData = [
    {
        id: 1,
        name: 'Silver',
        image: '/package/silver.webp',
        description: 'Silver Package APR Min Stake : 500 KSC',
        minStake: 500,
        maxStake: 4999,
        options: [
            {
                id: 1,
                name: '7 days',
                duration: 7,
                rate: 8,
                rateDisplay: 8.2,
                gift: '',
                poolLimit: 1000000,
                isDefault: false,
            },
            {
                id: 2,
                name: '30 days',
                duration: 30,
                rate: 20,
                rateDisplay: 20.1,
                gift: '',
                poolLimit: 2500000,
                isDefault: true,
            },
            {
                id: 3,
                name: '90 days',
                duration: 90,
                rate: 35,
                rateDisplay: 38.2,
                gift: '',
                poolLimit: UNLIMITED_KSC, // unlimited is 200000000 because KSC total is 200000000
                isDefault: false,
            },
            {
                id: 4,
                name: '180 days',
                duration: 180,
                rate: 55,
                rateDisplay: 62.7,
                gift: 'Random 10 got a Lootbox',
                poolLimit: UNLIMITED_KSC,
                isDefault: false,
            },
        ],
    },
    {
        id: 2,
        name: 'Gold',
        image: '/package/gold.webp',
        description: 'Gold Package APR Min: 5000 KSC',
        minStake: 5000,
        maxStake: 19999,
        options: [
            {
                id: 1,
                name: '7 days',
                duration: 7,
                rate: 10,
                rateDisplay: 10.3,
                gift: '',
                poolLimit: 1000000,
                isDefault: false,
            },
            {
                id: 2,
                name: '30 days',
                duration: 30,
                rate: 25,
                rateDisplay: 26.6,
                gift: '',
                poolLimit: 2500000,
                isDefault: false,
            },
            {
                id: 3,
                name: '90 days',
                duration: 90,
                rate: 40,
                rateDisplay: 44.1,
                gift: 'Random 20 got a Lootbox',
                poolLimit: UNLIMITED_KSC, // unlimited is 200000000 because KSC total is 200000000
                isDefault: true,
            },
            {
                id: 4,
                name: '180 days',
                duration: 180,
                rate: 65,
                rateDisplay: 75.8,
                gift: 'Random 30 got a Lootbox',
                poolLimit: UNLIMITED_KSC,
                isDefault: false,
            },
        ],
    },
    {
        id: 3,
        name: 'Ruby',
        image: '/package/ruby.webp',
        description: 'Ruby Package APR Min: 20,000 KSC',
        minStake: 20000,
        maxStake: 39999,
        options: [
            {
                id: 1,
                name: '7 days',
                duration: 7,
                rate: 12,
                rateDisplay: 12.4,
                gift: '',
                poolLimit: 1000000,
                isDefault: false,
            },
            {
                id: 2,
                name: '30 days',
                duration: 30,
                rate: 35,
                rateDisplay: 38.2,
                gift: 'Top 10 got a NFT Lootbox',
                poolLimit: 2500000,
                isDefault: false,
            },
            {
                id: 3,
                name: '90 days',
                duration: 90,
                rate: 50,
                rateDisplay: 56.4,
                gift: 'Top 30 got a NFT Lootbox',
                poolLimit: UNLIMITED_KSC, // unlimited is 200000000 because KSC total is 200000000
                isDefault: true,
            },
            {
                id: 4,
                name: '180 days',
                duration: 180,
                rate: 70,
                rateDisplay: 82.5,
                gift: 'Got a NFT Lootbox',
                poolLimit: UNLIMITED_KSC,
                isDefault: false,
            },
        ],
    },
    {
        id: 4,
        name: 'Diamond',
        image: '/package/diamond.webp',
        description: 'Diamond Package APR Min: 40,000 KSC',
        minStake: 40000,
        maxStake: UNLIMITED_KSC,
        options: [
            {
                id: 1,
                name: '7 days',
                duration: 7,
                rate: 15,
                rateDisplay: 15.6,
                gift: '',
                poolLimit: 1000000,
                isDefault: false,
            },
            {
                id: 2,
                name: '30 days',
                duration: 30,
                rate: 45,
                rateDisplay: 50.2,
                gift: 'Top 30 got a NFT Lootbox',
                poolLimit: 2500000,
                isDefault: false,
            },
            {
                id: 3,
                name: '90 days',
                duration: 90,
                rate: 60,
                rateDisplay: 69.2,
                gift: 'Got a Lootbox + Top 30 got a NFT race car',
                poolLimit: UNLIMITED_KSC, // unlimited is 200000000 because KSC total is 200000000
                isDefault: false,
            },
            {
                id: 4,
                name: '180 days',
                duration: 180,
                rate: 80,
                rateDisplay: 96.3,
                gift: 'Got a NFT rare car',
                poolLimit: UNLIMITED_KSC,
                isDefault: true,
            },
        ],
    },
]

export default PackageData